info:
  name: /action
  type: http
  seq: 3

http:
  method: POST
  url: "{{host}}/api/action"
  headers:
    - name: Authorization
      value: "{{secret}}"
  body:
    type: json
    data: |-
      {
        "player_id": "rolf",
        "game_id": "e484675c-2886-4834-8db1-bb5a827cb57f-1",
        "action": "all_in"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
